### GEOMETRY
/Geometry/TestGeomTilesThesis/visibility true
/Geometry/TestGeomTilesThesis/tile_type FBK
/Geometry/TestGeomTilesThesis/n_tile_rows 1
/Geometry/TestGeomTilesThesis/n_tile_columns 1

/Geometry/TestGeomTilesThesis/tile_vis true
/Geometry/TestGeomTilesThesis/tile_refl 0.
/Geometry/TestGeomTilesThesis/sipm_time_binning 5. picosecond
/Geometry/TestGeomTilesThesis/sipm_pde 0.3

### GENERATOR
/Generator/SingleParticle/particle geantino
/Generator/SingleParticle/min_energy 1  eV
/Generator/SingleParticle/max_energy 1 keV
/Generator/SingleParticle/region CENTER

#/Actions/PetSensorsEventAction/min_charge 50

### PHYSICS
#/process/optical/processActivation Scintillation true
#/process/optical/processActivation Cerenkov      true

### VERBOSITIES
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

/nexus/random_seed 132323

### OUTPUT FILE
/nexus/persistency/start_id 0
/nexus/persistency/outputFile test_geom_0.pet
